New endpoint
faigtherpinilla/backend pull request #10
Opened 2024-02-19 23:46 UTC by G10Amaya

cree un nuevo endpoint con la propiedad params

2024-02-19 23:52 UTC, yeissonpigo requested changes

2024-02-19 23:52 UTC, yeissonpigo commented on src/index.js
> +//})
Estos comentarios no aportan nada al código. Por favor remover.

2024-02-19 23:59 UTC, yeissonpigo approved these changes

2024-02-20 00:02 UTC, JohannBarajas commented
OK

2024-02-20 00:04 UTC, JohannBarajas approved these changes

2024-02-20 00:18 UTC, merged